/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthContainer: typeof import('./src/components/auth/AuthContainer.vue')['default']
    AuthForm: typeof import('./src/components/auth/AuthForm.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HeaderPage: typeof import('./src/components/layout/HeaderPage.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    HomeSlide1: typeof import('./src/components/homeSlides/HomeSlide1.vue')['default']
    HomeSlide2: typeof import('./src/components/homeSlides/HomeSlide2.vue')['default']
    HomeSlide3: typeof import('./src/components/homeSlides/HomeSlide3.vue')['default']
    ProfileForm: typeof import('./src/components/auth/ProfileForm.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide2Card: typeof import('./src/components/homeSlides/Slide2Card.vue')['default']
    Slide3Card: typeof import('./src/components/homeSlides/Slide3Card.vue')['default']
    TrainingPlan: typeof import('./src/components/TrainingPlan.vue')['default']
  }
}
