services:
  hack_front:
    container_name: hack_front
    build: .
    env_file: ".env"
    volumes:
       - .:/app
       - /app/node_modules/ 
       - ./nginx.conf:/etc/nginx/nginx.conf
       - certbot_data:/etc/letsencrypt
       - certbot_www:/var/www/certbot
    ports:
      - '443:4000'
      - '80:4000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app.loadbalancer.server.port=4000"
      - "traefik.http.routers.app.rule=Host(`example.com`)"
    networks:
      - web
  
  certbot:
    image: certbot/certbot
    volumes:
      - certbot_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d example.com -d www.example.com

volumes:
  certbot_data:
  certbot_www:

networks:
  web: