services:
  hack_front:
    container_name: hack_front
    build: .
    env_file: ".env"
    volumes:
       - .:/app
       - /app/node_modules/ 
       - ./nginx.conf:/etc/nginx/nginx.conf
      #  - certbot_data:/etc/letsencrypt
      #  - certbot_www:/var/www/certbot
    ports:
      - '443:443'
      - '80:80'
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app.loadbalancer.server.port=443"
      - "traefik.http.routers.app.rule=Host(`hackatonsite.jumpingcrab.com`)"
    networks:
      - web
  
  certbot:
    image: certbot/certbot
    volumes:
      - certbot_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --register-unsafely-without-email --agree-tos --no-eff-email -d hackatonsite.jumpingcrab.com

volumes:
  certbot_data:
  certbot_www:

networks:
  web: